In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, X):
        return X - X.mean()

In [3]:
clayer = CenteredLayer()
X = torch.Tensor([1, 2, 3])
clayer(X)

tensor([-1.,  0.,  1.])

In [10]:
net = nn.Sequential(nn.Linear(4, 8), CenteredLayer())
Y = net(torch.rand(4, 4))
Y.mean()

tensor(7.4506e-09, grad_fn=<MeanBackward0>)

In [11]:
class Mylinear(nn.Module):
    def __init__(self, n_inp, n_out):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(n_inp, n_out))
        self.bias = nn.Parameter(torch.rand(n_out, ))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [12]:
dense = Mylinear(5, 3)

In [13]:
dense(torch.rand(2, 5))

tensor([[1.4677, 0.4470, 1.2910],
        [2.0693, 0.4909, 2.3110]])

In [14]:
net = nn.Sequential(Mylinear(5, 3), Mylinear(3, 1))
net(torch.rand(2, 5))

tensor([[2.4570],
        [2.4587]])