In [1]:
from d2l import torch as d2l
import torch
import torch.nn as nn

In [2]:
def corr2d(X, K):
    h = X.shape[0] - K.shape[0] + 1
    w = X.shape[1] - K.shape[1] + 1
    
    r = torch.zeros(h, w)
    
    for i in range(h):
        for j in range(w):
            r[i, j] = (X[i:i + K.shape[0], j:j + K.shape[1]]*K).sum()
    return r

In [3]:
def corr2d_multi_in(Xs, Ks):
    return sum(corr2d(X, k) for X, k in zip(Xs, Ks))
Xs = [torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]]), torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])]
Ks = [torch.tensor([[0, 1], [2, 3]]), torch.tensor([[1, 2], [3, 4]])]
corr2d_multi_in(Xs, Ks)

tensor([[ 56.,  72.],
        [104., 120.]])

In [16]:
def corr2d_multi_in_out(Xs, Ks):
    return torch.stack([corr2d_multi_in(Xs, K) for K in Ks], 0)
K = torch.tensor([[[0, 1], [2, 3]], [[1, 2], [3, 4]]])
Ks = torch.stack((K, K + 1, K + 2), 0)
corr2d_multi_in_out(Xs, Ks)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [18]:
def corr2d_multi_in_out_1x1(X, K):
    # kernel size: co x ci x h x w
    # X: ci x img_h x img_w
    # K: co x ci x h x w
    ci, img_w, img_h = X.shape
    co, ci, k_w, k_h = K.shape
    return torch.matmul(K.reshape((co, ci)), X.reshape((ci, img_w*img_h))).reshape((co, img_h, img_w))
X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))

corr2d_multi_in_out_1x1(X, K)

tensor([[[-0.1691, -0.5782,  0.6436],
         [ 0.4650,  1.8764, -0.4876],
         [ 1.0876,  0.2725, -0.5169]],

        [[-0.0073, -0.4264,  0.1918],
         [ 0.2002,  1.0314, -0.3691],
         [ 0.6581,  0.0816, -0.3182]]])

In [19]:
corr2d_multi_in_out(X, K)

tensor([[[-0.1691, -0.5782,  0.6436],
         [ 0.4650,  1.8764, -0.4876],
         [ 1.0876,  0.2725, -0.5169]],

        [[-0.0073, -0.4264,  0.1918],
         [ 0.2002,  1.0314, -0.3691],
         [ 0.6581,  0.0816, -0.3182]]])